-- Last updated: 8/1/2025, 10:34:19 PM
# Write your MySQL query statement below
SELECT PROJECT.project_id,ROUND(AVG(EMPLOYEE.EXPERIENCE_YEARS),2) AS average_years FROM PROJECT
 INNER JOIN EMPLOYEE ON PROJECT.EMPLOYEE_ID=EMPLOYEE.EMPLOYEE_ID
 GROUP BY PROJECT.PROJECT_ID;